// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLrdADKJUR-WqzOJ2d5d3OPf3akYoHpaM',
    appId: '1:1091538466581:web:2cca749f502da88a34db1c',
    messagingSenderId: '1091538466581',
    projectId: 'crud-4e269',
    authDomain: 'crud-4e269.firebaseapp.com',
    storageBucket: 'crud-4e269.firebasestorage.app',
    measurementId: 'G-BWQ6264KM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMPe9-05dAkNheOqmL1UMKCdiEjGBgPHA',
    appId: '1:1091538466581:android:22d10b7f18617cfb34db1c',
    messagingSenderId: '1091538466581',
    projectId: 'crud-4e269',
    storageBucket: 'crud-4e269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhipFq1drGDoA670wTbaebPH6uiD3R-JM',
    appId: '1:1091538466581:ios:4eddcec7e362ebf034db1c',
    messagingSenderId: '1091538466581',
    projectId: 'crud-4e269',
    storageBucket: 'crud-4e269.firebasestorage.app',
    iosBundleId: 'com.example.b25Oposiciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhipFq1drGDoA670wTbaebPH6uiD3R-JM',
    appId: '1:1091538466581:ios:4eddcec7e362ebf034db1c',
    messagingSenderId: '1091538466581',
    projectId: 'crud-4e269',
    storageBucket: 'crud-4e269.firebasestorage.app',
    iosBundleId: 'com.example.b25Oposiciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLrdADKJUR-WqzOJ2d5d3OPf3akYoHpaM',
    appId: '1:1091538466581:web:38b63cf42e854f3834db1c',
    messagingSenderId: '1091538466581',
    projectId: 'crud-4e269',
    authDomain: 'crud-4e269.firebaseapp.com',
    storageBucket: 'crud-4e269.firebasestorage.app',
    measurementId: 'G-1LG38W1EC5',
  );
}
